### ISSUE TITLE
Visual Code Tasks: Readme file mentions Verify DB task not appearing in task list

### ISSUE THREAD

**Issue by Muppity** [microsoft/azuresql-devcontainers#22]
Hi, I was checking the DevContainer,
Found a README.md within the src->"dotnet" structure, and metions a Verify Database task (Line 73-76)
Didnt find it under the tasks, Imagine this is an old reference maybe.
<img width="892" alt="SC4" src="https://github.com/microsoft/azuresql-devcontainers/assets/26259648/4be386ab-4685-40f7-a007-89e74bc17903">

<img width="478" alt="SC5" src="https://github.com/microsoft/azuresql-devcontainers/assets/26259648/0ef6d50d-1820-41c1-a9cc-d5d0f0c92eb3">

**Comment by croblesm** [comment]
Thanks for the feedback @Muppity. As discussed offline, I will make some documentation changes to clarify how these tasks should be call it from VS Code.
